server:
  port: 3000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

jmx:
  rmi:
    host: localhost
    port: 8088

druid:
  security:
    username: monitor
    password: password
  url: jdbc:mysql://127.0.0.1:3306/suspnp_db?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&cachePrepStmts=true&useServerPrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useSSL=false
  username: root
  password: ABOCN18618331097
  driver-class-name: com.mysql.jdbc.Driver
  initialSize: 5
  minIdle: 5
  maxActive: 10
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: select '1+1'
  testWhileIdle: true

logging:
  level:
    com.evtape: DEBUG
  config: classpath:logger-dev.xml